# Generated by Django 3.1.2 on 2022-03-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processing',
            old_name='price',
            new_name='subtotal',
        ),
        migrations.RemoveField(
            model_name='processing',
            name='address',
        ),
    ]
