# Generated by Django 3.1.2 on 2022-03-02 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='user',
        ),
        migrations.DeleteModel(
            name='processing',
        ),
        migrations.DeleteModel(
            name='shipping',
        ),
    ]
