# Generated by Django 3.1.2 on 2022-03-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_orders_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='email',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
