# Generated by Django 3.1.2 on 2022-03-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_processingorders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='processingorders',
        ),
    ]
