# Generated by Django 3.1.2 on 2022-03-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_delete_processingorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='zip',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
