# Generated by Django 3.1.2 on 2022-03-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_orders_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
