# Generated by Django 3.1.2 on 2022-03-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_orders_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
