# Generated by Django 3.1.2 on 2022-04-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_orders_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='guestuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('macaddress', models.CharField(max_length=10000)),
            ],
        ),
    ]
