# Generated by Django 3.1.2 on 2022-04-22 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_guestuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestuser',
            name='macaddress',
        ),
        migrations.RemoveField(
            model_name='guestuser',
            name='password',
        ),
    ]
