# Generated by Django 3.1.2 on 2022-04-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_otp_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
    ]
