# Generated by Django 3.1.2 on 2022-04-27 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0021_confirmed_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestuser',
            name='name',
        ),
        migrations.AddField(
            model_name='guestuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
