# Generated by Django 3.1.2 on 2022-05-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20220427_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuser',
            name='ip',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
