# Generated by Django 3.1.2 on 2022-05-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_guestuser_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='premaccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('ip', models.CharField(max_length=10000)),
            ],
        ),
    ]
