# Generated by Django 3.1.2 on 2022-05-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_premaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='prevaccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre', models.CharField(blank=True, max_length=10000, null=True)),
                ('new', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
