# Generated by Django 3.1.2 on 2022-05-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20220524_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='econfirmed',
            name='email',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
