# Generated by Django 3.1.2 on 2022-10-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20220622_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='id_data',
            field=models.CharField(blank=True, max_length=532, null=True),
        ),
    ]
