# Generated by Django 3.1.2 on 2023-02-07 05:42

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_cart_id_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaddres',
            name='address',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100000, null=True)),
        ),
        migrations.AlterField(
            model_name='myaddres',
            name='city',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=250, null=True)),
        ),
        migrations.AlterField(
            model_name='myaddres',
            name='zip',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=1000, null=True)),
        ),
        migrations.AlterField(
            model_name='selected',
            name='address',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100000, null=True)),
        ),
        migrations.AlterField(
            model_name='selected',
            name='city',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=250, null=True)),
        ),
        migrations.AlterField(
            model_name='selected',
            name='zip',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=1000, null=True)),
        ),
    ]
