# Generated by Django 3.1.2 on 2023-02-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_auto_20230207_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaddres',
            name='address',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='myaddres',
            name='city',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='myaddres',
            name='zip',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='selected',
            name='address',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='selected',
            name='city',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='selected',
            name='zip',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
